# Generated by Django 2.2.1 on 2020-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='avg_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='pub_year',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
