# Generated by Django 2.2.1 on 2020-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0002_auto_20200228_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
