# Generated by Django 2.2.1 on 2020-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrec', '0003_orders_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
